### ISSUE TITLE
AddonContentsFinder

### ISSUE THREAD

**Issue by adambennett55** [aers/FFXIVClientStructs#1072]
do you know if theres data somewhere in the window to know how many in the Index are The non click headers? like are there no collision nodes for them, and if so is there a way to determine what there specific indexes are? like maybe an array of non collision headers and their indexes? is that possible?

**Comment by Haselnussbomber** [comment]
You can iterate over the [AddonContentsFinder.DutyList](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Client/UI/AddonContentsFinder.cs#L35)->[Items](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentTreeList.cs#L13) vector.
Inside the AtkComponentTreeListItem will find StringValues and UIntValues.
The first uint value is always the value of the [AtkComponentTreeListItemType](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Component/GUI/AtkComponentTreeList.cs#L53) enum.

**Comment by adambennett55** [comment]
oh awesome tysm, now if we can get the SelectedRow fixed i'd be all set :)

**Comment by adambennett55** [comment]
although I did find the actual value that SelectedRow is supposed to be giving us in the AtkValues list, but i dont know enough about this memory stuff to know if that index changes or if it remains the same, if it stays the same i can just use that value
