### ISSUE TITLE
Unable to build FFXIVClientStructs

### ISSUE THREAD

**Issue by RedWine82** [aers/FFXIVClientStructs#1086]
I seem to be unable to build the project. I get the following errors (there's over 2500 of them, I'm only including a few):
```
AtkUnitBase.cs(15, 65): [CS0246] The type or namespace name 'FixedSizeArray32<>' could not be found (are you missing a using directive or an assembly reference?)
UserFileEvent.cs(13, 66): [CS0246] The type or namespace name 'FixedSizeArray12<>' could not be found (are you missing a using directive or an assembly reference?)
ActionManager.cs(153, 25): [CS8795] Partial method 'ActionManager.StartCooldown(ActionType, uint)' must have an implementation part because it has accessibility modifiers.
RaptureAtkModule.cs(124,32): Error CS8377 : The type 'RaptureAtkModule.ItemCache' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'InheritsAttribute<T>'
RaptureAtkModule.cs(129,32): Error CS8377 : The type 'RaptureAtkModule.ItemCache' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'InheritsAttribute<T>'
```
I'm using the project solution file and Rider 2024.1.4. Is there something else I should be using instead?

**Comment by acapper** [comment]
I have also seen this issue since for a while now. I think these may have been introduced around the time of this commit https://github.com/aers/FFXIVClientStructs/commit/335df9f3f4c2c3b48c5a80295969dbc8334a2ce8 but I only occasionally build this so I'm not 100% sure.

**Comment by Haselnussbomber** [comment]
I'm using Visual Studio 2022 Version 17.11 Preview 5, and have absolutely no problems building the project.
Maybe try to build the InteropGenerator on its own first? 🤔

**Comment by acapper** [comment]
I'm using dotnet (8.0.204) command line via VS Code. 
Can build InteropGenerator fine with `dotnet build .\InteropGenerator.csproj`
When running `dotnet build .\FFXIVClientStructs.sln` I see the same errors mentioned by @RedWine82
Possible I am missing something that is installed at setup by Visual Studio though.

**Comment by RedWine82** [comment]
[build.txt](https://github.com/user-attachments/files/16603025/build.txt)
I did exactly like @acapper. I can build InteropGenerator.csproj just fine in the command line but not FFXIVClientStructs.sln.

I've attached the build output, if it helps.

**Comment by Haselnussbomber** [comment]
Can you try to build it with the newest SDK? (SDK 8.0.400) 🤔
https://dotnet.microsoft.com/download/dotnet/8.0

And if you're having issues in Rider too, then check the MSBuild version in Settings > Build, Execution, Deployment > Toolset and Build. (This is from an answer I found on stackoverflow. I'm not using Rider myself.)

**Comment by RedWine82** [comment]
> Can you try to build it with the newest SDK? (SDK 8.0.400) 🤔 https://dotnet.microsoft.com/download/dotnet/8.0
> 
> And if you're having issues in Rider too, then check the MSBuild version in Settings > Build, Execution, Deployment > Toolset and Build. (This is from an answer I found on stackoverflow. I'm not using Rider myself.)

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:27.82
```

That worked! thanks :)
