### ISSUE TITLE
Ida 9 support?

### ISSUE THREAD

**Issue by mistahmikey** [aers/FFXIVClientStructs#1235]
Just tried a "fullrun" using ida 9 and it failed.  Before I post a bunch of information about it, just wanted to make sure it is expected to run correctly with the new version.  If not, are there any plans to make it compatible with ida 9?

**Comment by wolfcomp** [comment]
This is currently expected and won't be fixed until I get IDA 9 or someone else decides to take the time to make sure it works between both IDA 7/8 and 9
The reason for this is they changed how the Structs and Enums work in IDA 9 so the entire way to insert the last portion of the fullrun fails.

IDA 9 currently should only work with `ffxiv_idarename.py`

**Comment by wolfcomp** [comment]
IDA 9 has completely redone the Type system, so nothing works at all with the other 2 scripts. If you want to use those import with IDA 8 and then upgrade with IDA 9 as I'm not dealing with figuring out bad IDA docs again for the next month just to get it working.
