### ISSUE TITLE
ffxiv_idarename.py doesn't work with Ghidra

### ISSUE THREAD

**Issue by NotNite** [aers/FFXIVClientStructs#143]
```
ffxiv_idarename.py> Running...
  File "W:\bullshit\ghidra\ffxiv\FFXIVClientStructs\ida\ffxiv_idarename.py", line 619
    def recurse_tree(current_node: Node, current_class: FfxivClass, all_bases: set[str]):
                                ^
SyntaxError: mismatched input ':' expecting RPAREN
ffxiv_idarename.py> Finished!
```

Seems to be [this](https://github.com/aers/FFXIVClientStructs/commit/919b5f53ae9defdb8f41990ea961a06e8e357509#diff-bb6b24bf13999272b27006f7711965f77861a326a30b43b9b1852a500ad68ac7) commit breaking it - type hinting isn't in py2, which Ghidra uses.

**Comment by aers** [comment]
Yeah, just removing the type hinting should be fine.

**Comment by aers** [comment]
This is fixed now.
