### ISSUE TITLE
Consider switching from source generator to generated-and-committed code

### ISSUE THREAD

**Issue by philpax** [aers/FFXIVClientStructs#233]
imo the source generator is quite hard to debug and use, especially if you'd like to view what their output looks like on GitHub.

I think it would be better to convert it to a standalone application that produces files that can be committed into the repository.

Open to arguments otherwise, though.

**Comment by aers** [comment]
![2022-08-25 20_56_04-FFXIVClientStructs – C__Users_aers_AppData_Local_Temp_SourceGeneratedDocuments_5](https://user-images.githubusercontent.com/1631648/186814301-4a715738-7cc4-49cd-9fba-529093caf24f.png)

I'm just unconvinced committing these files is worthwhile. IDEs are aware of them so debugging should also be aware of them.
