### ISSUE TITLE
Removing data from py rename script

### ISSUE THREAD

**Issue by daemitus** [aers/FFXIVClientStructs#28]
I know how much you love updating your diff scripts. This seems sane enough, although if you want it in json instead, i can make that happen. The idea is simple enough, take the actual data out of the py script into a yml file.

```
version: 2020.12.29.0000.0000

globals:
  0x14169A2A0: g_HUDScaleTable

functions:
  0x140059670: FFXIVString_ctor  # empty string ctor

classes:
  Client::Game::Control::TargetSystem::ListFeeder:
  
  GroupManager:
    funcs:
      0x140BB2600: Create
  Common::Configuration::ConfigBase:
    inherits_from: Client::System::Common::NonCopyable
    vtbl: 0x14164E260
    funcs:
      0x140068C30: ctor
  Common::Configuration::UIConfig:
    inherits_from: Common::Configuration::ConfigBase 
    vtbl: 0x14164E280
  Client::System::Framework::Framework:
    vtbl: 0x14164F4B8
    vfuncs:
      1: Setup
    funcs:
      0x14008EA40: ctor
```

**Comment by aers** [comment]
I absolutely prefer yaml or similar to json. This format looks fine to me. Sometime in the future (likely after next week cause I'll be busy) I'm gonna write some codegen stuff so having this in a separate file is a first step for that already. So thanks for doing it lol.

**Comment by daemitus** [comment]
It could be interesting to codegen from this and not have to write sigs. just delegate(imagebase + file offset - 0x140000000).

**Comment by aers** [comment]
Yep one point would to be able to include all the offset and vtbl functions as actual functions on the structs with the offsets done automatically.
