### ISSUE TITLE
Patch 6.5 - ConfigOption enum off by one

### ISSUE THREAD

**Issue by Meowchestra** [aers/FFXIVClientStructs#628]
Hi, you're probably still working on updating FFXIVClientStructs but just wanted to let you know this enum seems to be off by one now.

https://github.com/aers/FFXIVClientStructs/blob/8d9cbaea5db885e13a7a0f9ff43761c2a492b231/FFXIVClientStructs/FFXIV/Client/UI/Misc/ConfigOption.cs#L197

My plugin code which is now hitting BGM instead of master.
```
        /// <summary>
        /// Mutes/Unmutes the sound
        /// </summary>
        /// <param name="enabled"></param>
        public static unsafe void SetMasterSoundEnable(bool enabled)
        {
            Framework.Instance()->SystemConfig.CommonSystemConfig.ConfigBase.ConfigEntry[(int)ConfigOption.IsSndMaster].SetValueUInt((uint)(enabled ? 0 : 1));
        }

        public static unsafe bool GetMasterSoundEnable()
        {
            if (Framework.Instance()->SystemConfig.CommonSystemConfig.ConfigBase.ConfigEntry[(int)ConfigOption.IsSndMaster].Value.UInt == 0)
                PluginLog.Debug("Enabled");
            return (Framework.Instance()->SystemConfig.CommonSystemConfig.ConfigBase.ConfigEntry[(int)ConfigOption.IsSndMaster].Value.UInt == 0);
        }
```

**Comment by Haselnussbomber** [comment]
Heya,

I pinged Cara, which has a script to update this (if they can find it 😁).

Assuming you're using Dalamud, I also wanted to tell you that there is a GameConfig service, which is safer to use.

```cs
[PluginService] public static IGameConfig GameConfig { get; private set; }
```

With that, you can use it like this:

```cs
public static unsafe void SetMasterSoundEnable(bool enabled)
{
    Service.GameConfig.Set(SystemConfigOption.IsSndBgm, enabled);
}

public static unsafe bool GetMasterSoundEnable()
{
    return Service.GameConfig.TryGet(SystemConfigOption.IsSndBgm, out bool isSndBgm) && isSndBgm;
}
```

These enums are safer to use, since GameConfig looks up values by name instead of index (as seen by their attribute).
Alternatively, you can use their names directly:

```cs
public static unsafe void SetMasterSoundEnable(bool enabled)
{
    Service.GameConfig.System.Set("IsSndBgm", enabled);
}

public static unsafe bool GetMasterSoundEnable()
{
    return Service.GameConfig.System.TryGet("IsSndBgm", out bool isSndBgm) && isSndBgm;
}
```

Hope this helps! 🙂

**Comment by Meowchestra** [comment]
@Haselnussbomber That is actually super helpful, thanks so much! I imported the GameConfig service and migrated over to it and everything seems to work exactly how I want now toggling the master volume on and off instead of setting values 0 & 1.

```
        public static void SetMasterSoundEnable(bool enabled)
        {
            Api.GameConfig?.Set(SystemConfigOption.IsSndMaster, !enabled);
        }

        public static bool GetMasterSoundEnable()
        {
            return Api.GameConfig != null && Api.GameConfig.TryGet(SystemConfigOption.IsSndMaster, out bool isSndMaster) && isSndMaster;
        }
```

I'll leave this ticket open so the enum could be fixed up (or decided by maintained) but super happy with GameConfig existing!
