### ISSUE TITLE
ffxiv_idarename.py generating a lot of errors with latest FFXIV version

### ISSUE THREAD

**Issue by mistahmikey** [aers/FFXIVClientStructs#699]
Hello,

I am getting quite a few errors when I run this macro.  They are of the sort:

7FF67FB4E810: can't rename byte as 'vtbl_Client::UI::AddonTooltip' because this byte can't have a name (it is a tail byte).
7FF67FB675A8: can't rename byte as 'vtbl_Client::UI::AddonCharaSelectWorldServer' because this byte can't have a name (it is a tail byte).
7FF67FBB5F98: can't rename byte as 'vtbl_Client::UI::AddonWeeklyPuzzle' because this byte can't have a name (it is a tail byte).
7FF67FBBD2A0: can't rename byte as 'vtbl_Client::UI::AddonMJIRecipeNoteBook' because this byte can't have a name (it is a tail byte).

and 

Error: Function at 0x7FF67EA5E730 had unexpected name "" during naming of Client::Game::UI::RecipeNote.CancelCrafting
Error: Function at 0x7FF67EA5F690 had unexpected name "" during naming of Client::Game::UI::RecipeNote.IsRecipeUnlocked
Error: Function at 0x7FF67EA5FC00 had unexpected name "" during naming of Client::Game::UI::RecipeNote.FirstRecipeIndex
Error: Function at 0x7FF67EA5FBC0 had unexpected name "" during naming of Client::Game::UI::RecipeNote.GetRecipeByIndex
Error: Function at 0x7FF67EA5FC40 had unexpected name "" during naming of Client::Game::UI::RecipeNote.GetSelectedRecipe
Error: Function at 0x7FF67EA607A0 had unexpected name "" during naming of Client::Game::UI::RecipeNote.Initialize

probably hundreds of them.  I did put the ida.cfg file in place.  Is there something else I must do to not get these errors?  Or is this normal?

Thanks.

**Comment by pohky** [comment]
make sure you are running the script in on the most recent version of the game
you always need to create a new idb for the new exe after a patch (also wait for the analysis finished before running any scripts)

**Comment by mistahmikey** [comment]
I am using the most recent version of the script on the most recent very of the game - the 5.51 hotfix.  I deleted my existing idapro databases, started an analysis from scratch, and after the autoanalysis completed, I ran the subject script against the results of the static analysis (did not attach the debugger to a running ffxiv process), and still got all the errors. I even turned off the option that automatically applies lumina.  I am running the script using the "Script File" menu option.  I even uninstalled ida, reinstalled it, and repeated what I just described.  Attached is a file containing all the error messages. 
[issue.log](https://github.com/aers/FFXIVClientStructs/files/13356956/issue.log)
Is this not happening to anyone else?

**Comment by pohky** [comment]
yes you need to fix those yourself, the empty names are because the function at that address isn't disassembled and the wrong names are because they got a non-default label by the analyzer, OutdoorTerritory and RaptureAtkHistory errors are expected and can be ignored
